# Generated by Django 5.0.1 on 2024-02-01 09:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email адрес')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенты сервиса',
                'ordering': ['-fullname'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Рассылка', max_length=50, verbose_name='название рассылки')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начать с')),
                ('ended_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='закончить к')),
                ('regularity', models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='M', max_length=1, verbose_name='периодичность')),
                ('status', models.CharField(blank=True, choices=[('ED', 'завершена'), ('CR', 'создана'), ('ST', 'запущена')], default='CR', max_length=2, null=True, verbose_name='статус рассылки')),
                ('all_recipient', models.BooleanField(default=True, verbose_name='отправить всем')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mailstream.message')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='получатель')),
                ('stream', models.ForeignKey(limit_choices_to={'all_recipient': False}, on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_status', models.CharField(choices=[('S', 'успешно'), ('E', 'с ошибкой')], max_length=1, verbose_name='Статус попытки')),
                ('last_attempt', models.DateTimeField()),
                ('response', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='получатель')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
