# Generated by Django 5.0.1 on 2024-01-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='regularity',
            field=models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='M', max_length=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(blank=True, choices=[('CL', 'завершена'), ('CR', 'создана'), ('ST', 'запущена')], max_length=2, null=True, verbose_name='Статус рассылки'),
        ),
    ]
