# Generated by Django 5.0.1 on 2024-02-01 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0002_alter_message_body_alter_stream_ended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='all_recipient',
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='stream',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='log',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='ended_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Завершение'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mailstream.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(default='Рассылка', max_length=50, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='regularity',
            field=models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='M', max_length=1, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(blank=True, choices=[('ED', 'завершена'), ('CR', 'создана'), ('ST', 'запущена')], default='CR', max_length=2, null=True, verbose_name='Текущий статус'),
        ),
        migrations.DeleteModel(
            name='MailList',
        ),
    ]
