# Generated by Django 5.0.1 on 2024-01-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0002_alter_client_comments_alter_stream_regularity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-fullname'], 'verbose_name': 'Клиент сервиса', 'verbose_name_plural': 'Клиенты сервиса'},
        ),
    ]
