# Generated by Django 5.0.1 on 2024-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0003_remove_stream_all_recipient_client_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='client',
            field=models.ManyToManyField(to='mailstream.client'),
        ),
    ]
