# Generated by Django 5.0.1 on 2024-01-10 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0003_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='post_time',
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='получатель'),
        ),
        migrations.AddField(
            model_name='log',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='stream',
            name='all_recipient',
            field=models.BooleanField(default=False, verbose_name='отправить всем'),
        ),
        migrations.AddField(
            model_name='stream',
            name='ended_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='закончить к'),
        ),
        migrations.AddField(
            model_name='stream',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mailstream.message'),
        ),
        migrations.AddField(
            model_name='stream',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начать с'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='regularity',
            field=models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='M', max_length=1, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(blank=True, choices=[('ED', 'завершена'), ('CR', 'создана'), ('ST', 'запущена')], default='CR', max_length=2, null=True, verbose_name='Статус рассылки'),
        ),
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='получатель')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Получатель рассылки',
                'verbose_name_plural': 'Получатели рассылки',
            },
        ),
    ]
