# Generated by Django 5.0.1 on 2024-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0004_stream_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='client',
            field=models.ManyToManyField(to='mailstream.client', verbose_name='Подписчик'),
        ),
    ]
