# Generated by Django 5.0.1 on 2024-01-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0004_remove_stream_post_time_log_client_log_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='name',
            field=models.CharField(default='Расылка', max_length=50, verbose_name='название рассылки'),
        ),
    ]
