# Generated by Django 5.0.1 on 2024-01-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0006_alter_maillist_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='all_recipient',
            field=models.BooleanField(default=True, verbose_name='отправить всем'),
        ),
    ]
