# Generated by Django 5.0.1 on 2024-02-03 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0006_stream_start_time_alter_client_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mailstream.message', verbose_name='Сообщение'),
        ),
    ]
