# Generated by Django 5.0.1 on 2024-01-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0007_alter_stream_all_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='regularity',
            field=models.CharField(choices=[('D', 'раз в день'), ('W', 'раз в неделю'), ('M', 'раз в месяц')], default='M', max_length=1, verbose_name='периодичность'),
        ),
    ]
