# Generated by Django 5.0.1 on 2024-02-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0008_alter_stream_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailstream.client', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='log',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailstream.stream', verbose_name='Рассылка'),
        ),
    ]
