# Generated by Django 5.0.1 on 2024-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailstream', '0009_alter_log_client_alter_log_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='last_attempt',
        ),
        migrations.AddField(
            model_name='log',
            name='attempt_date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='attempt_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
