# Generated by Django 5.0.1 on 2024-02-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogstream', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
