# Generated by Django 5.0.1 on 2024-02-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogstream', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
